### ISSUE TITLE
Device does not disconnect

### ISSUE THREAD

**Issue by gharshaw** [espruino/EspruinoHub#116]
@gfwilliams  I have a device that once connected via a "/ble/notify" will not disconnect.  I'm expecting that is would timeout after 20 sec even though the device continues to transmit data.
I quote you from a previous issue #53  "If we do what you suggest then once connected to a device that keeps transmitting data, that's it. You can no longer disconnect and receive advertising so EspruinoHub is pretty much bricked :("  

This is the situation I find myself in. Is there a mqtt command I can send that will force a disconnect?
Thanks

**Comment by gfwilliams** [comment]
Thanks - I just fixed this, so now it should disconnect unless you write or keep sending `ping`

**Comment by gharshaw** [comment]
@gfwilliams , Thanks for the quick fix  - I was also able to add a "disconnect" topic that gives me granular control over the disconnect. I added it to the mqttclient.js file. I attached the file and changes are commented with "GSH" should you like to add it officially.
Thanks again 
[mqttclient.js.txt](https://github.com/espruino/EspruinoHub/files/13718568/mqttclient.js.txt)

**Comment by gfwilliams** [comment]
Thanks! Would you be able to turn that into a GitHub pull request? If so I'm very happy to add it in

**Comment by gharshaw** [comment]
I gave it a go. Not sure I did the pull request correctly Sent from my iPhoneOn Dec 19, 2023, at 12:32 PM, Gordon Williams ***@***.***> wrote:﻿
Thanks! Would you be able to turn that into a GitHub pull request? If so I'm very happy to add it in

**Comment by gfwilliams** [comment]
Thanks, however I'm not seeing it here - I've just pulled in the changes manually though
