### ISSUE TITLE
send MQTT

### ISSUE THREAD

**Issue by roansaiya** [espruino/EspruinoHub#17]
hai, i want to know is there a way to make a delay when sending mqtt data, i want to send data like every 1 minutes or else not every 1 second like default espruinoHub does.., thank you.

**Comment by gfwilliams** [comment]
Hi,

Normal advertising MQTT packets are sent when advertising data is received, and there's no built-in way to stop that. However you could comment out the `mqtt.send` commands at places like this: https://github.com/espruino/EspruinoHub/blob/master/lib/discovery.js#L77

Once you remove that code, actual decoded service data is updated only every minute or if it changes: https://github.com/espruino/EspruinoHub/blob/master/lib/discovery.js#L99

**Comment by roansaiya** [comment]
thanks a lot for the answer,, im gonna try it now..
