### ISSUE TITLE
Bluetooth advertising blocking

### ISSUE THREAD

**Issue by nofoxgit** [espruino/EspruinoHub#18]
Hi, 

Are there any way I can switch off advertising of my RPi bluetooth ?? I'm using it only to read beacons presence in my house, I don't need http proxy. I only want my RPi with EspruinoHub to read beacons presence. Now my RPi advertising and I can connect to it with BLE apps on my phone and so anyone of my neighbours can.. I think its dangerous to my devices. And when I connect to it, the communication with my beacons are blocked.. Is it possible to turn off advertising ??

**Comment by gfwilliams** [comment]
I don't believe it is possible via config at the moment, but you could try just commenting out this line: https://github.com/espruino/EspruinoHub/blob/master/index.js#L18

It'd be a good addition though.

> I think its dangerous to my devices

There's a config item for `httpProxy` which is off by default - while anyone can connect to the Pi (which would stop you receiving advertising as you say) they won't be able to make HTTP requests or actually do anything destructive.

**Comment by nofoxgit** [comment]
Thanks for your response!  I've just commented out the line and it works! My raspberry pi is invisible!

**Comment by gfwilliams** [comment]
I've not made this automatic if http_proxy is false
