### ISSUE TITLE
Error while installing EspruinoHub

### ISSUE THREAD

**Issue by schneemaa** [espruino/EspruinoHub#19]
Hi everybody
I'm new here and I need your help. I'm trying to connect my Ruuvitags with Openhab. So I'm to install node-red which works fine and EspruinoHub.
I did all steps like the description. But at the point where I have to `npm install` this comes out:
>pi@raspberrypi:~ $ cd EspruinoHub
>pi@raspberrypi:~/EspruinoHub $ npm install
> usb@1.3.1 install /home/pi/EspruinoHub/node_modules/usb
> node-pre-gyp install --fallback-to-build
>node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v57-linux-arm.tar.gz 
>node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
>make: Entering directory '/home/pi/EspruinoHub/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o

Does anyone know what I can do?
Thank you so much

**Comment by gfwilliams** [comment]
What does the rest of the log say? It looks from that log message like it's all ok. It couldn't find the `usb` module, but then it starts building it for itself.

**Comment by schneemaa** [comment]
> [11:32:05] openhabian@openHABianPi:~/EspruinoHub$ npm install
> usb@1.3.1 install /home/openhabian/EspruinoHub/node_modules/usb
> node-pre-gyp install --fallback-to-build
>node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v48-linux-arm.tar.gz 
>node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@6.13.1 (node-v48 ABI, glibc) (falling back to source compile with node-gyp) 
>make: Entering directory '/home/openhabian/EspruinoHub/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
  CXX(target) Release/obj.target/usb_bindings/src/device.o
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /home/openhabian/EspruinoHub/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/openhabian/EspruinoHub/node_modules/usb/build'

> bluetooth-hci-socket@0.5.1 install /home/openhabian/EspruinoHub/node_modules/bluetooth-hci-socket
> node-gyp rebuild

>make: Entering directory '/home/openhabian/EspruinoHub/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:
../src/BluetoothHciSocket.cpp:275:72: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /home/openhabian/.node-gyp/6.13.1/include/node/v8.h:25:0,
                 from /home/openhabian/.node-gyp/6.13.1/include/node/node.h:42,
                 from /home/openhabian/.node-gyp/6.13.1/include/node/node_buffer.h:4,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/openhabian/.node-gyp/6.13.1/include/node/v8.h:3272:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/openhabian/.node-gyp/6.13.1/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/openhabian/EspruinoHub/node_modules/bluetooth-hci-socket/build'

> websocket@1.0.25 install /home/openhabian/EspruinoHub/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/openhabian/EspruinoHub/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/openhabian/EspruinoHub/node_modules/websocket/build'
EspruinoHub@0.0.0 /home/openhabian/EspruinoHub
├─┬ bleno@0.4.2 
│ ├─┬ bluetooth-hci-socket@0.5.1 
│ │ └─┬ usb@1.3.1 
│ │   └─┬ node-pre-gyp@0.6.39 
│ │     ├── detect-libc@1.0.3 
│ │     ├─┬ hawk@3.1.3 
│ │     │ ├── boom@2.10.1 
│ │     │ ├── cryptiles@2.0.5 
│ │     │ ├── hoek@2.16.3 
│ │     │ └── sntp@1.0.9 
│ │     ├─┬ mkdirp@0.5.1 
│ │     │ └── minimist@0.0.8 
│ │     ├─┬ nopt@4.0.1 
│ │     │ ├── abbrev@1.1.1 
│ │     │ └─┬ osenv@0.1.5 
│ │     │   ├── os-homedir@1.0.2 
│ │     │   └── os-tmpdir@1.0.2 
│ │     ├─┬ npmlog@4.1.2 
│ │     │ ├─┬ are-we-there-yet@1.1.4 
│ │     │ │ └── delegates@1.0.0 
│ │     │ ├── console-control-strings@1.1.0 
│ │     │ ├─┬ gauge@2.7.4 
│ │     │ │ ├── aproba@1.2.0 
│ │     │ │ ├── has-unicode@2.0.1 
│ │     │ │ ├── object-assign@4.1.1 
│ │     │ │ ├── signal-exit@3.0.2 
│ │     │ │ ├─┬ string-width@1.0.2 
│ │     │ │ │ ├── code-point-at@1.1.0 
│ │     │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│ │     │ │ │   └── number-is-nan@1.0.1 
│ │     │ │ ├─┬ strip-ansi@3.0.1 
│ │     │ │ │ └── ansi-regex@2.1.1 
│ │     │ │ └── wide-align@1.1.2 
│ │     │ └── set-blocking@2.0.0 
│ │     ├─┬ rc@1.2.6 
│ │     │ ├── deep-extend@0.4.2 
│ │     │ ├── ini@1.3.5 
│ │     │ ├── minimist@1.2.0 
│ │     │ └── strip-json-comments@2.0.1 
│ │     ├─┬ request@2.81.0 
│ │     │ ├── aws-sign2@0.6.0 
│ │     │ ├── aws4@1.6.0 
│ │     │ ├── caseless@0.12.0 
│ │     │ ├─┬ combined-stream@1.0.6 
│ │     │ │ └── delayed-stream@1.0.0 
│ │     │ ├── forever-agent@0.6.1 
│ │     │ ├─┬ form-data@2.1.4 
│ │     │ │ └── asynckit@0.4.0 
│ │     │ ├─┬ har-validator@4.2.1 
│ │     │ │ ├─┬ ajv@4.11.8 
│ │     │ │ │ └── co@4.6.0 
│ │     │ │ └── har-schema@1.0.5 
│ │     │ ├─┬ http-signature@1.1.1 
│ │     │ │ ├── assert-plus@0.2.0 
│ │     │ │ ├─┬ jsprim@1.4.1 
│ │     │ │ │ ├── assert-plus@1.0.0 
│ │     │ │ │ ├── extsprintf@1.3.0 
│ │     │ │ │ ├── json-schema@0.2.3 
│ │     │ │ │ └─┬ verror@1.10.0 
│ │     │ │ │   └── assert-plus@1.0.0 
│ │     │ │ └─┬ sshpk@1.14.1 
│ │     │ │   ├── asn1@0.2.3 
│ │     │ │   ├── assert-plus@1.0.0 
│ │     │ │   ├── bcrypt-pbkdf@1.0.1 
│ │     │ │   ├─┬ dashdash@1.14.1 
│ │     │ │   │ └── assert-plus@1.0.0 
│ │     │ │   ├── ecc-jsbn@0.1.1 
│ │     │ │   ├─┬ getpass@0.1.7 
│ │     │ │   │ └── assert-plus@1.0.0 
│ │     │ │   ├── jsbn@0.1.1 
│ │     │ │   └── tweetnacl@0.14.5 
│ │     │ ├── isstream@0.1.2 
│ │     │ ├── json-stringify-safe@5.0.1 
│ │     │ ├─┬ mime-types@2.1.18 
│ │     │ │ └── mime-db@1.33.0 
│ │     │ ├── oauth-sign@0.8.2 
│ │     │ ├── performance-now@0.2.0 
│ │     │ ├── qs@6.4.0 
│ │     │ ├── stringstream@0.0.5 
│ │     │ ├─┬ tough-cookie@2.3.4 
│ │     │ │ └── punycode@1.4.1 
│ │     │ ├── tunnel-agent@0.6.0 
│ │     │ └── uuid@3.2.1 
│ │     ├── rimraf@2.6.2 
│ │     ├── semver@5.5.0 
│ │     ├─┬ tar@2.2.1 
│ │     │ ├── block-stream@0.0.9 
│ │     │ └─┬ fstream@1.0.11 
│ │     │   └── graceful-fs@4.1.11 
│ │     └─┬ tar-pack@3.4.1 
│ │       ├── fstream-ignore@1.0.5 
│ │       └── uid-number@0.0.6 
│ ├── bplist-parser@0.0.6 
│ └─┬ debug@2.6.9 
│   └── ms@2.0.0 
├─┬ mqtt@2.16.0 
│ ├─┬ commist@1.0.0 
│ │ ├── leven@1.0.2 
│ │ └── minimist@1.2.0 
│ ├─┬ concat-stream@1.6.1 
│ │ └── typedarray@0.0.6 
│ ├─┬ end-of-stream@1.4.1 
│ │ └─┬ once@1.4.0 
│ │   └── wrappy@1.0.2 
│ ├─┬ help-me@1.1.0 
│ │ ├── callback-stream@1.1.0 
│ │ ├─┬ glob-stream@6.1.0 
│ │ │ ├── extend@3.0.1 
│ │ │ ├─┬ glob@7.1.2 
│ │ │ │ ├── fs.realpath@1.0.0 
│ │ │ │ ├── inflight@1.0.6 
│ │ │ │ ├─┬ minimatch@3.0.4 
│ │ │ │ │ └─┬ brace-expansion@1.1.11 
│ │ │ │ │   ├── balanced-match@1.0.0 
│ │ │ │ │   └── concat-map@0.0.1 
│ │ │ │ └── path-is-absolute@1.0.1 
│ │ │ ├─┬ glob-parent@3.1.0 
│ │ │ │ ├─┬ is-glob@3.1.0 
│ │ │ │ │ └── is-extglob@2.1.1 
│ │ │ │ └── path-dirname@1.0.2 
│ │ │ ├── is-negated-glob@1.0.0 
│ │ │ ├── ordered-read-streams@1.0.1 
│ │ │ ├─┬ pumpify@1.4.0 
│ │ │ │ └── pump@2.0.1 
│ │ │ ├── remove-trailing-separator@1.1.0 
│ │ │ ├─┬ to-absolute-glob@2.0.2 
│ │ │ │ └─┬ is-absolute@1.0.0 
│ │ │ │   ├─┬ is-relative@1.0.0 
│ │ │ │   │ └─┬ is-unc-path@1.0.0 
│ │ │ │   │   └── unc-path-regex@0.1.2 
│ │ │ │   └── is-windows@1.0.2 
│ │ │ └─┬ unique-stream@2.2.1 
│ │ │   ├─┬ json-stable-stringify@1.0.1 
│ │ │   │ └── jsonify@0.0.0 
│ │ │   └── through2-filter@2.0.0 
│ │ └── through2@2.0.3 
│ ├── inherits@2.0.3 
│ ├── minimist@1.2.0 
│ ├─┬ mqtt-packet@5.5.0 
│ │ ├── bl@1.2.1 
│ │ ├── process-nextick-args@2.0.0 
│ │ └── safe-buffer@5.1.1 
│ ├── pump@3.0.0 
│ ├─┬ readable-stream@2.3.5 
│ │ ├── core-util-is@1.0.2 
│ │ ├── isarray@1.0.0 
│ │ ├── string_decoder@1.0.3 
│ │ └── util-deprecate@1.0.2 
│ ├── reinterval@1.1.0 
│ ├── split2@2.2.0 
│ ├─┬ websocket-stream@5.1.2 
│ │ ├─┬ duplexify@3.5.4 
│ │ │ └── stream-shift@1.0.0 
│ │ └─┬ ws@3.3.3 
│ │   ├── async-limiter@1.0.0 
│ │   └── ultron@1.1.1 
│ └── xtend@4.0.1 
├─┬ noble@1.9.0 
│ └─┬ debug@2.2.0 
│   └── ms@0.7.1 
└─┬ websocket@1.0.25 
  ├── nan@2.9.2 
  ├─┬ typedarray-to-buffer@3.1.5 
  │ └── is-typedarray@1.0.0 
  └── yaeti@0.0.6 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/bleno/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

**Comment by schneemaa** [comment]
That's all from the output. I tried it again and the EspruinoHub seems to work after I typed './start.sh'. I see my Ruuvitags and can access the WebIDE.
But I'm struggling with something else. When I use the commands:
>sudo cp systemd-EspruinoHub.service /etc/systemd/system/EspruinoHub.service
and 
>sudo systemctl start EspruinoHub.service && sudo journalctl -f -u EspruinoHub

This output follows:
>^C[12:03:43] openhabian@openHABianPi:~/EspruinoHub$  sudo systemctl start EspinoHub.service && sudo journalctl -f -u EspruinoHub
-- Logs begin at Thu 2016-11-03 18:16:42 CET. --
Mar 16 11:40:21 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 11:40:21 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 11:40:21 openHABianPi systemd[1]: EspruinoHub.service: Start request repeated too quickly.
Mar 16 11:40:21 openHABianPi systemd[1]: Failed to start EspruinoHub BLE -> MQTT bridge.
Mar 16 11:40:21 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 11:40:21 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:56 openHABianPi systemd[1]: Started EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:56 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=217/USER
Mar 16 12:03:56 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:56 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 12:03:57 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: Started EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=217/USER
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 12:03:57 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: Started EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=217/USER
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 12:03:57 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: Started EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=217/USER
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 12:03:57 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: Started EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=217/USER
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:57 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.
Mar 16 12:03:58 openHABianPi systemd[1]: EspruinoHub.service: Service hold-off time over, scheduling restart.
Mar 16 12:03:58 openHABianPi systemd[1]: Stopped EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:58 openHABianPi systemd[1]: EspruinoHub.service: Start request repeated too quickly.
Mar 16 12:03:58 openHABianPi systemd[1]: Failed to start EspruinoHub BLE -> MQTT bridge.
Mar 16 12:03:58 openHABianPi systemd[1]: EspruinoHub.service: Unit entered failed state.
Mar 16 12:03:58 openHABianPi systemd[1]: EspruinoHub.service: Failed with result 'exit-code'.

That doesn't seem to be working properly.
Thank you for your help :)

**Comment by gfwilliams** [comment]
Ok, so it looks like the install actually worked fine.

Your problem with the start script is almost certainly that you're not installing under a normal `pi` user, but as `openhabian`, so the path of your home directory will be different.

Edit the file `systemd-EspruinoHub.service` and change the paths around, then repeat the steps for installing the service.

**Comment by schneemaa** [comment]
Thanks. I changed now the paths and user to 'openhabian'. But it's still not working.
>Mar 16 13:36:03 openHABianPi systemd[1]: EspruinoHub.service: Main process exited, code=exited, status=210/CHROOT

What else do I need to change?
Thanks for your help

**Comment by schneemaa** [comment]
It's working now. Thank you for your Help :D

**Comment by gfwilliams** [comment]
Great! Any idea what you changed, in case others hit this issue?

**Comment by schneemaa** [comment]
After I edited the file `systemd-EspruinoHub.service` I needed to reboot my raspberry.
