### ISSUE TITLE
Commands do not work anymore

### ISSUE THREAD

**Issue by eastehr** [espruino/EspruinoHub#24]
Hello Gordon, 

I have a function blink(). When I call this (either from WEB-IDE or Nordic from my mobile) it blinks the LED. So far so good. Now I try to connect to this via MQTT: mosquitto_pub -t "/ble/write/e5:c8:14:d4:de:27/nus/nus_tx" -m "blink();\n"

But nothing happens, though it did work before. Do you have any ideas?

**Comment by eastehr** [comment]
This is the output from the status log (I included a few further comments). MQTT says: /ble/write/... and immidiately afterwards /ble/written/... 

I also tried another syntax 
mosquitto_pub -t "/ble/write/e5:c8:14:d4:de:27/nus/nus_tx" -m $'blink();\n'

 Scanning stopped.
 e5:c8:14:d4:de:27: Connecting...
 Connected.
 Write: Got connected device
 e5:c8:14:d4:de:27: Getting Service...
 e5:c8:14:d4:de:27: found service: 6e400001b5a3f393e0a9e50e24dcca9e
 e5:c8:14:d4:de:27: found characteristic: 6e400002b5a3f393e0a9e50e24dcca9e
 wrote data: "blink();\n" 9 bytes
 e5:c8:14:d4:de:27: Written.
 Connection: Switch from busy to non-busy
 e5:c8:14:d4:de:27: Disconnecting due to lack of use (after 10 secs)
 e5:c8:14:d4:de:27: Disconnecting.
 e5:c8:14:d4:de:27: Disconnected
 Scanning started.

**Comment by eastehr** [comment]
Funny: DE gets a German flag :-)

**Comment by eastehr** [comment]
Good morning, 

after long trial and error it works now without apparent changes. However, I believe that the startup process is not working properly on the raspberry. I included sleep 5s in the startup.sh at the beginning and sometimes it seems to start something duplicate so that ports are already in use. After a day it still stopped working. 

Unfortuantely I am not a big expert in Linux, so I can't properly check for its preconditions. 

Best Regards
Ernst

**Comment by gfwilliams** [comment]
Is it possible that you added *both* the startup options - both Headless and Console? You only need one or the other.

The other possibility is if you happened to send some kind of opening bracket over Bluetooth in a previous message. Espruino bracket-counts to determine whether to execute, so:

```
blink();
// works
blink(
);
// works
(
...
blink();
// won't work until the brackets are aligned
```

To reset that you can just send a `ctrl-c` character (`\x03`) first and it'll clear the current line of input - however if everything is working fine then it shouldn't be needed.

**Comment by eastehr** [comment]
So it is more stable with a complete reinstallation. However, I still need to be careful not to start the start.sh twice (the second start will break both). And I still need to have a delay in start.sh. 
But as long as it works I am happy, I suppose:-)

**Comment by gfwilliams** [comment]
By running start.sh twice you mean running it twice *at the same time*?

I'd advise maybe using the 'headless' mode instead if it's causing trouble. That does have code in there specifically to avoid the service being run twice, but it's designed to run as a background task (so no on-screen debug info unless you access localhost:1888/status or run the `journalctl` command)
