### ISSUE TITLE
How do I get a bluetooth broadcast device

### ISSUE THREAD

**Issue by zhangqi0328** [espruino/EspruinoHub#29]
How to get a MAC for a nearby bluetooth radio device, by subscribing to what topics

**Comment by gfwilliams** [comment]
Can you give any more information? I have no idea what you're asking I'm afraid.

**Comment by zhangqi0328** [comment]
After the raspberry pi scans a nearby bluetooth BLE device, what topic does the PC subscribe to get the MAC of the bluetooth BLE device

**Comment by gfwilliams** [comment]
Check out https://github.com/espruino/EspruinoHub#advertising

It just publishes a topic `/ble/advertise/ma:ca:dd:re:ss` - so just subscribe to `/ble/advertise/#` and pull the address out of the topic name

**Comment by zhangqi0328** [comment]
thank you，I can now subscribe to the MAC number of my bluetooth BLE device
