### ISSUE TITLE
nordic nrf52840 running Circuitpython

### ISSUE THREAD

**Issue by Tasm-Devil** [espruino/EspruinoHub#30]
Hi there.

I found this, searching for an BLE nordic UART Service to MQTT relay.
I'am using Circuitpython and i am wondering if I can use your software to get a connection to my NRF52840 running Circuitpython.

Do you think this is possible?

**Comment by gfwilliams** [comment]
Yes, I think it'd work absolutely fine. There's nothing Espruino-specific about what this project does. 

There are some examples of doing Nordic UART via MQTT here: https://github.com/espruino/EspruinoHub#connections
