### ISSUE TITLE
How to uninstall EspruinoHub?

### ISSUE THREAD

**Issue by sebi5361** [espruino/EspruinoHub#33]
I use EspruinoHub with my Puck.js on a regular basis. I would like to uninstall it in order to install the equivalent docker container. Could you provide some instructions on how to uninstall it properly?

**Comment by gfwilliams** [comment]
Hi! I'll update the docs. If you installed as in the README then:

```
sudo systemctl stop EspruinoHub.service
sudo systemctl disable EspruinoHub.service
sudo rm /etc/systemd/system/EspruinoHub.service
sudo rm -rf ~/EspruinoHub
```

Should do it

**Comment by sebi5361** [comment]
Thank you.
