### ISSUE TITLE
Connection refused: not authorized

### ISSUE THREAD

**Issue by Arnooooo** [espruino/EspruinoHub#35]
The default configuration doesn't set a client ID. One of the basic settings of the mosquitto broker is requiring a (unique) client ID. The fix is pretty easy; always set a default client ID (e.g. espruinohub). I've stared myself crazy at this issue. I hope to make a pull request to modify the default config for the mqtt_options section tomorrow.

**Comment by gfwilliams** [comment]
Thanks - it'd be perfect if you could do that PR.

Interesting though as I've been using it with default installs of `mosquitto` for ages - maybe mosquitto has changed recently.
