### ISSUE TITLE
Mqtt topic shouldn't start with leading slash

### ISSUE THREAD

**Issue by Arnooooo** [espruino/EspruinoHub#38]
According to advisories, the leading slash for an MQTT topic shouldn't be used.

Source:
https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

Whats your thought? I recognize that it would be annoying for existing users if this changes, but I think it's not nice to have this extra 'null' topic.

Proposal; configurable topic prefix, which defaults to '/ble' ?

**Comment by gfwilliams** [comment]
Yes, I found out it was not ideal, but as you say had to keep it as-is to avoid annoying existing users.

A configurable prefix sounds like a great solution to the problem

**Comment by Arnooooo** [comment]
I'll try to add this option somewhere during this week

**Comment by gfwilliams** [comment]
Closing this as changes merged
