### ISSUE TITLE
Add another hci ID to config

### ISSUE THREAD

**Issue by pavoroby** [espruino/EspruinoHub#40]
Add the choice of a bluetooth adapter to the config. When you want to use several of them a certain one, and not the one that has more id.

**Comment by gfwilliams** [comment]
Is it not possible to just set an environment variable when running EspruinoHub? https://github.com/noble/noble#multiple-adapters

`NOBLE_HCI_DEVICE_ID=1 ...` should do it

**Comment by pavoroby** [comment]
> Is it not possible to just set an environment variable when running EspruinoHub? https://github.com/noble/noble#multiple-adapters
> 
> `NOBLE_HCI_DEVICE_ID=1 ...` should do it

Of course you can. But how? In which file do you need to add this parameter?

But still. Why not add this to your EspruinoHub settings? Convenience.

**Comment by gfwilliams** [comment]
You just add it to start.sh here: https://github.com/espruino/EspruinoHub/blob/master/start.sh#L9

So it's a one liner that does everything. We can add docs for it, but I don't think there's any need for a specific setting.

**Comment by pavoroby** [comment]
> You just add it to start.sh here: https://github.com/espruino/EspruinoHub/blob/master/start.sh#L9
> 
> So it's a one liner that does everything. We can add docs for it, but I don't think there's any need for a specific setting.

You're right. Close Issue
