### ISSUE TITLE
data conversion on notification not working

### ISSUE THREAD

**Issue by rmcubed** [espruino/EspruinoHub#42]
In my sample application, my bluetooth device (in this case a TurnTouch button) returns a 2-byte buffer. This is working correctly. However in the event handler set up in notify for data events this is constrained into a string: 

`
char.on('data', function (data) {
         //snipped
         if (connection.services[serviceUUID][characteristicUUID].notifyCallback)
           connection.services[serviceUUID][characteristicUUID].notifyCallback(data.toString());
       });
`

For me this always results in the same 4-byte array being returned i.e. 0xefbfbd00, irrespective of the value of data.  I believe this is a string conversion issue. The application for me works correctly when the string conversion is removed, i.e. simply 

`
char.on('data', function (data) {
         //snipped
         if (connection.services[serviceUUID][characteristicUUID].notifyCallback)
           connection.services[serviceUUID][characteristicUUID].notifyCallback(data);
       });
`

This change may be a breaking change for any app that is expecting a string.

Pull request follows.

**Comment by gfwilliams** [comment]
Actually no, I got confused. That doesn't work at all :)

Do you know exactly what buffer was returned so I can test? Pretty sure we just needed to specify `binary` encoding as I bet the data was something that got interpreted as a UTF-8 char

**Comment by rmcubed** [comment]
thanks, will definitely give this a go.
