### ISSUE TITLE
Post-connection request for servics can get into loop

### ISSUE THREAD

**Issue by rmcubed** [espruino/EspruinoHub#44]
If a connection fails before the list of services is acquired, it is possible to get into an infinite loop looking for services. The only cure seems to be to restart EspruinoHub.

A desirable behaviour might be to force close the connection if more than a certain number of service requests fail?

**Comment by gfwilliams** [comment]
Sounds like a plan - or maybe just limit the amount of times it'll try.

Do you know exactly where is gets stuck? Is it inside Noble?

**Comment by rmcubed** [comment]
I don't know. I've actually moved away from using EspruinoHub to connect/subscribe, it seemed to be creating something of a bluetooth storm (judging only by increased latency in other bluetooth devices on my network), but maybe that is the pi inbuilt bluetooth rather than anything about EspruinoHub. I instead moved to an ESP32 (Arduino since Espruino doesn't have bluetooth yet) connecting to the thing I need to monitor via BLE and bridging that into MQTT, which works well but runs into contention issues because of the ESP32's shared radio. Next step is to use either the ESP32 or the Puck to bridge from the bluetooth connection to advertise the results, then I don't need wifi on it. This is all to monitor a TurnTouch https://shop.turntouch.com/ which is a nicely aesthetic multitouch button.

**Comment by gfwilliams** [comment]
Closing this for now as I haven't encountered it myself and don't seem to be able to find a way to reproduce.

It might even have been related to the version of bluez installed on the device
