### ISSUE TITLE
"history_path" configuration parameter is not applied

### ISSUE THREAD

**Issue by maxkueng** [espruino/EspruinoHub#45]
Changing `history_path` configuration parameter in `config.json` has no effect and EspruinoHub uses the default value which is `/hist/`.

**Example**

config.json
```json
{
  "history_path": "yolo/"
}
```

**Comment by gfwilliams** [comment]
thanks - just fixed.

**Comment by maxkueng** [comment]
Oh, awesome! I was just about to start fixing it. Thank you!
