### ISSUE TITLE
Crash when viewing rssi.html or mqtt.html

### ISSUE THREAD

**Issue by jjok** [espruino/EspruinoHub#47]
When I view either of those pages EspruinoHub crashes with this error.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND hassio.local:1883
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hassio.local:1883'
}
```

**Comment by jjok** [comment]
It looks like a DNS-related problem when trying to look up the MQTT broker. I'm using a local name for the server here, but the same thing happened previously, when I was using the IP address.

The error above is when running in a Docker container on Linux. Presumably the same thing happens when running as a service on a Raspberry Pi 3, but I'm not sure how to find what the error is. I can see it causes the service to restart though.

**Comment by gfwilliams** [comment]
Looks like you might be specifying the port in the hostname, when it's not meant to be specified?

**Comment by jjok** [comment]
Hmm. Yes, I am doing that. If I take it out it fails to connect to the broker. Where are you meant to specify the port?
Are these the docs for the library that's used? https://github.com/mqttjs/MQTT.js/#client
It doesn't really mention port in there.

**Comment by gfwilliams** [comment]
Looks like https://github.com/mqttjs/MQTT.js/#mqttconnecturl-options might do it.

What happens if you just remove `:1883`? That seems to be the standard port number so I don't think it needs specifying

**Comment by jjok** [comment]
I've tried all the combinations that I can think of, and the only ones that will connect are:

```
"mqtt_host": "http://hostname.local:1883"
"mqtt_host": "http://ip-addess:1883"
```

I've tried:

```
"mqtt_host": "http://hostname.local"
"mqtt_host": "http://ip-address"
"mqtt_host": "mqtt://hostname.local"
"mqtt_host": "mqtt://ip-address"
"mqtt_host": "hostname.local"
"mqtt_host": "ip-address"
"mqtt_host": [{"host": "http://hostname.local", "port": 1883}]
"mqtt_host": [{"host": "http://ip-address", "port": 1883}]
"mqtt_host": [{"host": "mqtt://hostname.local", "port": 1883}]
"mqtt_host": [{"host": "mqtt://ip-address", "port": 1883}]
"mqtt_host": [{"host": "hostname.local", "port": 1883}]
"mqtt_host": [{"host": "ip-address", "port": 1883}]
```
