### ISSUE TITLE
Would be nice to be able to disable the history-functionality from config.json

### ISSUE THREAD

**Issue by GrumpyMeow** [espruino/EspruinoHub#49]
This would reduce the resource usage when it's not needed.

**Comment by gfwilliams** [comment]
I believe just not having the `log` directory should stop this? Maybe there's more that could be disabled though

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/EspruinoHub/commit/819c078d4b6f92428b8bb4c1c08ba87999d00e27
