### ISSUE TITLE
Not able to "read" when setting mqtt_prefix to "ble" in config.json (default "/ble")

### ISSUE THREAD

**Issue by GrumpyMeow** [espruino/EspruinoHub#50]
I'm unable to read data when i've overridden the mqtt_prefix to be "ble". It does work using "/ble" as prefix

**Comment by gfwilliams** [comment]
Do you have an example of what you're sending and what isn't working?

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/EspruinoHub/commit/819c078d4b6f92428b8bb4c1c08ba87999d00e27
