### ISSUE TITLE
Device disconnects even when notifications are being received.

### ISSUE THREAD

**Issue by GrumpyMeow** [espruino/EspruinoHub#53]
24:e5:aa:47:ad:cb: Getting Service...
 24:e5:aa:47:ad:cb: found service: 477ea600a26011e4ae370002a5d50002
 24:e5:aa:47:ad:cb: found characteristic: 477ea600a26011e4ae370002a5d54090
 24:e5:aa:47:ad:cb: startNotifications complete
 24:e5:aa:47:ad:cb: Disconnecting due to lack of use (after 20 secs)
 24:e5:aa:47:ad:cb: Disconnecting.
 24:e5:aa:47:ad:cb: Disconnected

**Comment by gfwilliams** [comment]
Is this because of code that you are running? This is intentional - you just need to send `/ble/ping/device` every so often.

The IDE should be a good example of this - it works fine.

Otherwise if the connection broke and your device didn't explicitly send a `disconnect` then EspruinoHub would just stay connected forever.

**Comment by GrumpyMeow** [comment]
Are you sure? I'm pretty sure the following part of your code will disconnect devices after a while (default 20 seconds). 
I'm now calling "connection.setUsed()" on every received notification to postpone the disconnection by this code:
https://github.com/espruino/EspruinoHub/blob/e8b9d947f2287f221fc59b0674fa1222d14a9080/lib/connect.js#L386-L394

My suggested change:
```
characteristic.on('data', function (data) {
         log(connection.name+": notification on "+JSON.stringify(data.toString('binary')));
         //new Uint8Array(data).buffer
         if (connection.services[serviceUUID][characteristicUUID].notifyCallback)
           connection.services[serviceUUID][characteristicUUID].notifyCallback(data.toString('binary'));
>>       connection.setUsed(); // Reset 'secondsSinceUsed' on notifyCallback triggered.
       });
```

**Comment by gfwilliams** [comment]
Yep, ping is here: https://github.com/espruino/EspruinoHub/blob/e8b9d947f2287f221fc59b0674fa1222d14a9080/lib/mqttclient.js#L123

It calls:

https://github.com/espruino/EspruinoHub/blob/e8b9d947f2287f221fc59b0674fa1222d14a9080/lib/connect.js#L368

which calls

https://github.com/espruino/EspruinoHub/blob/e8b9d947f2287f221fc59b0674fa1222d14a9080/lib/connect.js#L204

which calls

https://github.com/espruino/EspruinoHub/blob/e8b9d947f2287f221fc59b0674fa1222d14a9080/lib/connect.js#L173

Which sets `secondsSinceUsed` to 0.

So all you need to do is keep pinging the device via MQTT while you want to stay connected. The IDE does this and works great.

If we do what you suggest then once connected to a device that keeps transmitting data, that's it. You can no longer disconnect and receive advertising so EspruinoHub is pretty much bricked :(
