### ISSUE TITLE
Using multiple BLE dongles?

### ISSUE THREAD

**Issue by Ghuru42** [espruino/EspruinoHub#58]
I want to run node-red and espruinoHub on the same machine, with this I have run into an issue.
As soon as espruinoHub makes a connection the ble scanner in node-red stopps, and wont get any new messages until espruinoHub has closed it's connection and I restart node-red.

To work around this my first thought is to use two BLE dongles on the machine.
In this case its a RaspberryPi 4, so the internal BLE is HCI0, thats what node-red and noble defaults to.

So now I'm trying to make espruinoHub use HCI1 instead, but how ever I try this I cant get it to work.

In noble I found that setting NOBLE_HCI_DEVICE_ID=1 should make noble use HCI1.
But for what ever reason it either does not do this, or it does and it still conflicts with node-red.

The bigger picture here is that we use node-red to collect data from espruino devices, works great. And it would be amazing to be able to run espruinoHub on the same machine to be able to remotely change the JS code on devices.

**Comment by gfwilliams** [comment]
`NOBLE_HCI_DEVICE_ID=1` should work fine, and actually I use that here running some things at the same time (albeit not with Node RED). Have you tried `=0` and `=2` to see if you have any success?

What data are you collecting from Espruino devices with node-red though? EspruinoHub does a lot of scanning too, so it's easy to subscribe to the MQTT events created by that instead.
