### ISSUE TITLE
Debug messages look too much like HTML

### ISSUE THREAD

**Issue by jjok** [espruino/EspruinoHub#60]
... so Firefox tries to render it.

eg

    <HTTP>Some message

is assumed to be 

    <HTTP>Some message</HTTP>

and you end up with just 

    Some message

**Comment by gfwilliams** [comment]
Ahh, thanks! You mean in the log page?

In general we should probably turn them into &gt;/etc when displaying the log, but this is an easy fix

**Comment by jjok** [comment]
Yeah, the Status page. I wonder if it shouldn't try to render it as HTML as it's inside a `<pre>` element already. Difficult to say if it's a bug in Firefox or not.
