### ISSUE TITLE
Set presence to 0 for non-present `known devices` when the app starts.

### ISSUE THREAD

**Issue by plague-doctor** [espruino/EspruinoHub#67]
Could you please consider setting the presence to 0 when we have defined known devices but the device is not present when the EspruinoHub starts?
Occasionally I need to clean the MQTT broker (for test/maintenance reason) and when the EspruinoHub starts AND the known device is not available, its presence is not reported. This messes a bit with my automation.

**Comment by gfwilliams** [comment]
Just done.
