### ISSUE TITLE
Presense is flapping

### ISSUE THREAD

**Issue by plague-doctor** [espruino/EspruinoHub#68]
I started to observe this issue since the last update of bluez to version 5.50.
This is my config:
```
{
  "known_devices" : {
    "12:AA:AA:AA:AA:99" : "test",
  },
  "only_known_devices": true,
  "ble_timeout" : 0,
  "presence_timeout" : 10,
  "max_connections" : 4,
  "connection_timeout": 20,
  "advertised_services" : {
    "ffff" : {
      "name" : "level"
    }
  },
  "http_port" : 1888,
  "http_proxy" : false,
  "http_whitelist" : [
  ],
  "mqtt_host": "mqtt://mqtt.my.host,
  "mqtt_options": {
    "username": "mqtt_user",
    "password": "mqtt_passwd",
    "clientId": "clientid"
  },
  "mqtt_prefix": "bluetooth-test"
}
```
## Flapping

![Screenshot_20201204_083528](https://user-images.githubusercontent.com/10541916/101091518-2e2ab880-35b0-11eb-80b3-6443f9de2a25.png)

The `test` beacon sits all the time on the same spot (check the rssi?). As you can see the presence of my test device is flapping like crazy. Which renders the whole idea useless.
This does not happen right after I run the EspruinoHub. It begins acting that way after some time (5, 10, 30 minutes) it is very nondeterministic... But when it starts, it keeps going like that.

## MQTT Connected (over and over)

I have also noticed that EspruinoHub started to generate huge number of `[MQTT] Connected` messages. The start of the service service looks like that:
```
Dec 04 08:31:58 beacon ble-beacon[1248]: Starting without Bleno (GATT Server)
Dec 04 08:31:59 beacon ble-beacon[1248]: [Config] Config config.json loaded
Dec 04 08:31:59 beacon ble-beacon[1248]: [HTTPProxy] config.http_proxy=false, not enabling Bleno/Proxy
Dec 04 08:32:00 beacon ble-beacon[1248]: [MQTT] Connecting...
Dec 04 08:32:00 beacon ble-beacon[1248]: [HTTP] Server is listening on http://localhost:1888
Dec 04 08:32:00 beacon ble-beacon[1248]: [HTTP] www directory found at /opt/ble-beacon/www. Web server at http://localhost:1888
Dec 04 08:32:00 beacon ble-beacon[1248]: [History] history_path value is empty, thus not providing history.
Dec 04 08:32:00 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:00 beacon ble-beacon[1248]: [Discover] Noble StateChange: poweredOn
Dec 04 08:32:01 beacon ble-beacon[1248]: [Discover] Starting scan...
Dec 04 08:32:01 beacon ble-beacon[1248]: [Discover] Scanning started.
Dec 04 08:32:02 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:04 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:06 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:08 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:10 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:12 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:14 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:16 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:18 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:20 beacon ble-beacon[1248]: [MQTT] Connected
Dec 04 08:32:22 beacon ble-beacon[1248]: [MQTT] Connected
[...]
Dec 04 08:32:24 beacon ble-beacon[1248]: [MQTT] Connected
[...]
```
and it keeps polluting the log.

I am not sure what is causing this problem, as your solution was rock-solid before...

**Comment by gfwilliams** [comment]
Ahh - but you're connecting to an online MQTT server, not to localhost?

Does this happen if you use just the local server? It seems possible that the connection is getting dropped, and that could be causing the presence messages?

**Comment by gfwilliams** [comment]
Is this a possibility? https://github.com/knolleary/pubsubclient/issues/372 - eg there's another client with the same ID connecting to the server?

**Comment by plague-doctor** [comment]
Oh, shame on me - of course it was the cause! 
More even - I was very well aware of this issue. Just slipped out of the memory. Sorry!
