### ISSUE TITLE
new Dockerfile run on node:10-alpine

### ISSUE THREAD

**Issue by twocolors** [espruino/EspruinoHub#69]
What do you think about new Dockerfile run on node:10-alpine
```
FROM node:10-alpine AS build

RUN set -x \
  && apk add --no-cache --virtual .build-deps \
    build-base \
    linux-headers \
    eudev-dev \
    python \
    git \
  && git clone https://github.com/espruino/EspruinoHub /tmp/espruinohub \
  && cd /tmp/espruinohub \
  && npm i --production --verbose \
  && apk del .build-deps \
  && mkdir /app \
  && mv /tmp/espruinohub/node_modules /tmp/espruinohub/lib /tmp/espruinohub/www /tmp/espruinohub/index.js /tmp/espruinohub/config.json /app/ \
  && rm -rf /tmp/*

FROM node:10-alpine

COPY --from=build /app /app

RUN set -x \
  && apk add --no-cache tzdata

WORKDIR /app

CMD [ "node", "index.js", "-c", "/data/config.json" ]

```

**Comment by gfwilliams** [comment]
Isn't node 10 pretty much end of life in a few months? https://nodejs.org/en/about/releases/

If we're going to move to a different Node, I'd probably suggest using something newer?

**Comment by twocolors** [comment]
let's use node:12-alpine ? 
official docker node support more platform

**Comment by gfwilliams** [comment]
Sounds good to me! So this will still work on Raspberry Pi?

**Comment by twocolors** [comment]
on my pi4 work
```bash
pi@pi:~ $ docker image inspect espruinohub:latest | grep -i arm
        "Architecture": "arm",
```

@jjok can test on Pi Zero?

**Comment by gfwilliams** [comment]
If it works on Pi 4 then I bet the zero will be fine

**Comment by jjok** [comment]
This looks a lot simpler than the one I did. 👍

There are different versions of Node for armv6 and armv7. I'm not sure if it will know which you're using and give you the right version. I'll see if it works on a Pi Zero (or Pi 1, actually I'm just switching to).

Will it run on x64? I was just making some tweaks to the current one, so I can run it on my laptop for development.

**Comment by jjok** [comment]
The only other thing is that I had it so that you so build remotely like `docker build https://github.com...`. It just means that you don't need `git` as dependency when you're doing the build, so you only need to install `docker`. But I don't feel that strongly about it.

**Comment by twocolors** [comment]
all support OS/ARCH in this https://hub.docker.com/layers/node/library/node/12-alpine/images/sha256-a9ee412baa5c130dea5f8483e95890f8d7e499dda196973f4397189b0bb98244?context=explore

**Comment by jjok** [comment]
So you have to tell it which version you want when you do the build, I guess.

**Comment by twocolors** [comment]
it seems when you publish (hub.docker) must tell OS, check please going to pi 1 and x64

in this post see arch (build on pi4)
https://github.com/espruino/EspruinoHub/issues/69#issuecomment-738866241

**Comment by twocolors** [comment]
@jjok you not test this Dockerfile on pi and x64?

**Comment by jjok** [comment]
I haven't tried it yet. I'll see if I can try it this week.

**Comment by jjok** [comment]
I tried on my laptop.

    docker build -t espruino/espruinohub:alpine-test .
    docker run --rm --net=host --name espruinohub espruino/espruinohub:alpine-test 

I get this error. @twocolors Any idea?

```
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error relocating /app/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node: _ZN2v88internal35IsolateFromNeverReadOnlySpaceObjectEm: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by twocolors** [comment]
test this https://github.com/twocolors/EspruinoHub/blob/docker-node-12/Dockerfile

**Comment by werty1st** [comment]
i'm running this for a while now without problems: https://hub.docker.com/r/werty1st/espruinohub

https://github.com/werty1st/EspruinoHub-docker/blob/master/Dockerfile
