### ISSUE TITLE
Something has changed on the backend for EspruinoHub?

### ISSUE THREAD

**Issue by d3nd3** [espruino/EspruinoHub#83]
`VM11:1 

GET https://www.espruino.com/serial/ports 404 (Not Found)

index.js:92927 /serial/ports doesn't exist - disabling WebSocket support`

When I run EspruinoHub on my raspberry pi and access the Top Left

![image](https://user-images.githubusercontent.com/2523452/123996613-69b32700-d9c7-11eb-99b3-b8ed0334a78e.png)

EspruinoTools core/serial_websocket_relay.js
var getPorts=function(callback)  override.

> Espruino.Core.Utils.getJSONURL("/serial/ports", function(ports) {
        if (ports===undefined) {
          console.log("/serial/ports doesn't exist - disabling WebSocket support");

EspruinoWebIDE server.js

>     if (url == "/serial/ports") {
      Espruino.Core.Serial.getPorts(function(ports) {
        response.writeHead(200);
        response.end(JSON.stringify(ports,null,2));
      });
      return;
    }

Update: this error is there for direct use of IDE @ espruino.com/ide

**Comment by d3nd3** [comment]
im guna close the issue because it seems like your server just isnt running the server.js file which is fine. I will run it locally.

**Comment by gfwilliams** [comment]
EspruinoHub changed (a few years ago I think??) such that it just runs the IDE in an iframe and communicates that way. You get the `/serial/ports` error but it should still work fine.

The `/serial/ports` is (i think) for when running https://github.com/espruino/EspruinoWebIDE/blob/master/server.js locally. It's not on `espruino.com` at all as you noted.

**Comment by d3nd3** [comment]
Well, I have been using EspruinoHub on the raspberry pi to use its bluetooth for accessing the bangle.js.  It had been working for months, I didn't change anything. And now it stops working.. so I believe its likely due to this error? I dont remember seeing this error in the past either.  So perhaps there is more to it?

If the EspruinoHub is using serial/ports uri .. and it used them before, and it didn't 'Disable WebSockets' .. then how did it access that URI?  It would mean that espruino.com _was_ serving the serial/ports uri , can you confirm that?

**Comment by d3nd3** [comment]
Or do you have some extra advice for me to fix my espruinoHub :P

**Comment by d3nd3** [comment]
Btw, is there a way I can talk to you more casually about the source code? I'm trying to understand how some things work, like the relay feature eg. and have a question or two.  Where would be the best place to ask this?

**Comment by d3nd3** [comment]
Okay so we can perhaps assume that serial/ports is not my error .. then I wonder why the EspruinoHub isn't connecting to bluetooth hmm.. **thinking**

EspHub status :
> [HTTP] Websocket MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883
[HTTP] Websocket MQTT closed (MQTT)
[HTTP] Websocket MQTT closed (WebSocket)

NodeRed status :
> Jul 01 16:47:04 pizero Node-RED[328]: 1 Jul 16:47:04 - [info] [mqtt-broker:pizero] Connection failed to broker: mqtt://localhost:1883


Ok it seems something is wrong with my mosquitto mqtt broker.  The process is running but I see no port open on 1883.

**Comment by gfwilliams** [comment]
Yeah, so it looks to me like your mosquitto has an issue.

It could be a new version of mosquitto has disabled port 1883 (unencrypted) MQTT by default, and just uses 8883 for SSL.

I'd just enable it in the mosquitto config though. Requiring SSL when you're connecting to a server that's *on your own computer* and I believe isn't even accessible externally seems pretty wasteful
