### ISSUE TITLE
homeassistant.js not passing alert level

### ISSUE THREAD

**Issue by bouton** [espruino/EspruinoHub#94]
2a06 ble service alert level is available in lib/attributes as alert (line 188) but line 61 in lib/homeassistant.js is looking for "level" rather than "alert".

I changed in my local copy and seems to be passed now.

Are there any other files that need updating as well?

Thanks

**Comment by gfwilliams** [comment]
No, I think that's it. If you could issue a PR it'd be great!

**Comment by bouton** [comment]
Ummm what's a PR?

**Comment by gfwilliams** [comment]
PR = Pull Request

It's when you change the code yourself and then submit it back here as a suggested change. But I can do it here - did you change `lib/attributes` or `lib/homeassistant.js`? I guess changing the former could cause issues for other people using MQTT who were expecting the name to be `alert`.

Would just adding `  alert: {},` to homeassistant fix it?

**Comment by bouton** [comment]
Cool. I will give it a go next time.

For now I changed homeassistant.js level:{} to alert: {}

You might also want to change the example in config.json where you can
customize service names.  You use level as an example- I presume you were
thinking of alert?  Just wondering.
Thanks
Katherine

**Comment by gfwilliams** [comment]
Ok, great - just sorted. I added alert rather than changing `level` as I think some other BLE advertising types use `level` and if we changed it we'd break them.

I think the example in config.json is ok - sometimes people want to use `level` and not `alert`.
