### ISSUE TITLE
Only publish known devices

### ISSUE THREAD

**Issue by bouton** [espruino/EspruinoHub#95]
Is there anyway only to publish a white list of devices. I see known devices is listed but I can't get it tow work as the MQTT Broker keeps connecting and disconnecting when I set "only_known_devices" to true, then list the single device.  I see there was some mention of it and a possible fix in previous issues, but I see nothing in the documention?  I just keep getting hundreds of mac addresses published via the hub to home assistant as devices which I don't want. Thanks.

**Comment by gfwilliams** [comment]
I just tried it here and `only_known_devices:true` works fine for me, seems to do exactly what you want.

Assuming you're running it as a service, maybe try `sudo journalctl -f -u EspruinoHub` to see if you can figure out why it's connecting/disconnecting all the time?

**Comment by bouton** [comment]
Still researching.

**Comment by bouton** [comment]
Not sure what I did different. Rebooted a few times, re-wrote the config... Anyway seems to now work. Maybe a caching issue. I apologize - Thanks. Good to close.
