### ISSUE TITLE
Error with NPM install

### ISSUE THREAD

**Issue by itchensen** [espruino/EspruinoHub#96]
Hi,
i get an error when installing on my raspi zero with external bluetooth dongle

```
pi@rasbath:~/EspruinoHub $ npm install
npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.22.5 | linux | arm
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:444:11)
npm ERR! gyp ERR! stack     at Socket.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (net.js:676:12)
npm ERR! gyp ERR! System Linux 5.10.63+
npm ERR! gyp ERR! command "/usr/bin/node" "/home/pi/EspruinoHub/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/pi/EspruinoHub/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v12.22.5
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-27T08_07_11_842Z-debug.log
```

I followed the installation routine 'Installation of EspruinoHub and Web IDE'

Any hints or clues? Thanks!

**Comment by gfwilliams** [comment]
What version of Raspberry Pi OS are you on?

I've heard reports that the instructions don't work well on the new one, and you need the 'Legacy' OS

**Comment by itchensen** [comment]
Thanks for the hint - it solved my problems.
I've been on non-legacy one (Raspberry Pi OS Lite 32bit). Switched to legacy version and installation was successful.

There have been a hint saying something like "not promise anything due to nodejs 10.x" - should i go back and downgrade or is it worth trying since everything seems to be accessible?

**Comment by gfwilliams** [comment]
If it all works I'd keep with the Node.js version you have :)

**Comment by itchensen** [comment]
Thanks for your feedback / help. Everything seems to work fine for the moment.

**Comment by Werner-G** [comment]
I am facing the same problem during installation, and no directory /node_modules is created. I am using a RPi4 with 64bit OS light 'Bullseye'. Don't know what it means 'legacy' or 'non-legacy'. 
System:  Linux 5.10.103-v8+
node -v v12.22.5
node-gyp -v v3.8.0
npm v7.5.2
