### ISSUE TITLE
Inquiry to connect.js job queue

### ISSUE THREAD

**Issue by d3nd3** [espruino/EspruinoHub#99]
### Inquiry
I have been studying the connect.js and disovery.js attempting to learn how it works and possibly improve it. From what I observe there are a few edge cases where behavior might not be as intended and have experienced them first hand, but am not sure of the direct cause.

### JobQueue
Could you help me understand the role of the job queue in there, when is it intended to run the jobs. What happens if jobs build up faster than they are being ran (eg. 4 second timeouts).  Why does job queue exist?

### scanningRestart
Scanning restart requires `jobQueue.length` 0 and `connections.length` 0 , how is the jobQueue length meant to get to 0?

### sequential Firing? isBusy
Are the jobs (write,read,notify,etc) meant to be ran sequentially, like job1 -> callbackResponseJob1 -> job2 -> callbackResponsejob2, is that the purpose of isBusy gate ?

#### Race Condition or misunderstanding
`setNotBusy` opens the `BusyGate` and calls `serviceQueue` which `setTimeout(job,100)`.  If the `BusyGate` is opened, then is it true to say that a request from the 'mqttclient' (aka a live/fresh job) could get in before or after that 100ms.  So its saying that if there is 100ms of free time run a job, else run a fresh/live job.  Now i put it that way, it does make more sense and might not be a bug, would like you to confirm it though.
#### Disconnected but behave as if connected
If you disconnect from the Watch, either by `NRF.disconnect()` or move the watch out of range, since the IDE is never told the bluetooth state and sends a notify every 3 seconds, strange behavior occur. `onDisconnect` fires, then on parsing the 3sec notify , checks if device is connected/found, returns false and tries to make new Connection, if still out of range, the connection will wait because `setBusy` is true from notify Job still and the job body is not called because the callback is passed to `onConnected`.
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L253
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L63

 So `IsBusy` is true, every request is queued until the 1 Sec Interval Loop Opens the `BusyGate` because of `BusyTimeout` thus allowing another notify Job to be processed instead of queued.  Even though the connection has not 'fully connected', this time the `getConnectedDevice` returns found instead of not found, because the connection object created from previous hanging notify job is created before it's `onConnected` callback fires.
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L36-L40 

The notify job proceeds to `discoverCharacteristics` as if it is connected but its really in an unconnected/connecting state.   `setUsedCounter`  is also 0 because of `found` so the connection doesn't timeout.
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L249

 There is also a message in console `Possible EventEmitter memory leak 11 serviceDiscovr listeners added to peripheral` because they timeOut too, with the 4 sec timeout.   Even if it would timeout, I don't think it would be able to restartScanning because jobQueue.length would not be 0.
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L108
https://github.com/espruino/EspruinoHub/blob/e75de381ea2823693fe11f03bef5de4307f17830/lib/connect.js#L101

**Comment by d3nd3** [comment]
### IDE to be signalled to disconnect
I had idea that you could use the `/ble/presence` to signal to the IDE that the bluetooth connection is closed. Currently the IDE state does not change from connected to disconnected ever.  But since the EspruinoHub changes state to `scanning` when its not connected (atleast i think thats the intention), **and** presences are only published when `scanning`, any presence for that device would imply that the EHub is not connected to any device?.
### Might be cleaner to use the `device.state`
The device.state field has *"disconnected"* *"connecting"* *"connected"*. Handling these cases might make sense, to make it clear if we want to run code in fully connected state or not?

**Comment by gfwilliams** [comment]
Hi - this is a bit of a massive list, but I'll do what I can...

> Could you help me understand the role of the job queue in there. Why does job queue exist?

It seems you can only (reliably) connect to one device at a time, so the Job Queue is meant to queue up reads/writes to happen sequentially.

> What happens if jobs build up faster than they are being ran (eg. 4 second timeouts).

They just keep queuing up - I'm not sure I understand under what circumstances that would happen though

> Scanning restart requires jobQueue.length 0 and connections.length 0

You can't scan while a connection is open - so scanning stops, all jobs are executed, then it starts again

> how is the jobQueue length meant to get to 0?

All the jobs get executed??

> Are the jobs (write,read,notify,etc) meant to be ran sequentially, like job1 -> callbackResponseJob1 -> job2 -> callbackResponsejob2, is that the purpose of isBusy gate ?

Yes

> setNotBusy opens the BusyGate and calls serviceQueue which setTimeout(job,100). If the BusyGate is opened, then is it true to say that a request from the 'mqttclient' (aka a live/fresh job) could get in before or after that 100ms. So its saying that if there is 100ms of free time run a job, else run a fresh/live job. Now i put it that way, it does make more sense and might not be a bug, would like you to confirm it though.

I don't think it's intentional. I think `setTimeout(() => {setNotBusy(); job()},100)` is probably the intended behaviour.

Again the delay is because I think we were having some reliability issues if we just pushed things through as fast as possible.

> If you disconnect from the Watch, either by NRF.disconnect() or move the watch out of range, since the IDE is never told the bluetooth state and sends a notify every 3 seconds, strange behavior occur.

The idea is you should be able to just send the notify/ping every so often and EspruinoHub will keep trying to connect to it.

The lack of feeback about connection state is a pain I know, but potentially is a little tricky to fix nicely.

>  this time the getConnectedDevice returns found instead of not found, because the connection object created from previous hanging notify job is created before it's onConnected callback fires.

Definitely sounds like a bug. 

> I had idea that you could use the /ble/presence to signal to the IDE that the bluetooth connection is closed. Currently the IDE state does not change from connected to disconnected ever. 

> But since the EspruinoHub changes state to scanning when its not connected (atleast i think thats the intention), and presences are only published when scanning, any presence for that device would imply that the EHub is not connected to any device?

Yes, that's the idea. Presence should I think be a separate event since it's whether the device is within range. If the Bangle disconnects it can still be within range, just not connected.

> The device.state field has "disconnected" "connecting" "connected". Handling these cases might make sense, to make it clear if we want to run code in fully connected state or not?

Yes - maybe have a new `/ble/connected/DEVICE` topic that updates with the connected state?

However handling that nicely in the Web IDE may be a bit hacky since it expects the connection state to change in response to you clicking the 'connect' button - not automatically. It may be possible to handle it nicely though I guess

**Comment by d3nd3** [comment]
Thanks Gordon!
